### PR TITLE
update iframe content

### PR DESCRIPTION
**Pull request by Japitana-JohnWalter**
update argument.txt and iframe responsiveness

### CODE REVIEW

**Comment by go-christianharrel** [comment]
Hey, thanks for reaching out and completing your codes! We'll get back to you soon with the feedback we have gathered on your codespace. Stay tuned! 😊👍

**Review by Naoe-Adrian — CHANGES_REQUESTED** [review]
- [ ] remove space here 

https://github.com/PUP-BSIT/exercise-13-avengears/blob/ccc9c359579e0c650fc4cc2e4665569a7ff3138f/japitana_johnwalter/index.html#L13
 
enclosed it like this 

_`rel="stylesheet"/>`_

- [x] Avoidance of Broken Link

https://github.com/PUP-BSIT/exercise-13-avengears/blob/ccc9c359579e0c650fc4cc2e4665569a7ff3138f/japitana_johnwalter/index.html#L159

https://github.com/PUP-BSIT/exercise-13-avengears/blob/ccc9c359579e0c650fc4cc2e4665569a7ff3138f/japitana_johnwalter/index.html#L154

revise it like this
` <script src="./javascript/comment_section.js">`
` <iframe src="./argument.txt"></iframe>`

- About applying proper naming convention on ID .
Much better to use descriptive name. I suggest of using other meaningful terms. For example, what class, container, input and other attribute is that?



https://github.com/PUP-BSIT/exercise-13-avengears/blob/ccc9c359579e0c650fc4cc2e4665569a7ff3138f/japitana_johnwalter/index.html#L131

-use underscore if you have id name that consist of two words

it can be like this: user_comment
https://github.com/PUP-BSIT/exercise-13-avengears/blob/ccc9c359579e0c650fc4cc2e4665569a7ff3138f/japitana_johnwalter/index.html#L136

https://github.com/PUP-BSIT/exercise-13-avengears/blob/ccc9c359579e0c650fc4cc2e4665569a7ff3138f/japitana_johnwalter/index.html#L139-L141

if you change your id and classes name make sure change your js file for your code to run properly

**Comment by Japitana-JohnWalter** [comment]
all guideline issues are fixed

**Review by Naoe-Adrian — APPROVED** [review]
LGTM thank you for following the guidelines

**Pull request merged**
